[build]
  command = "./build.sh"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--no-optional"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function settings for Next.js API routes
[functions]
  external_node_modules = ["@tensorflow/tfjs-node"]
  included_files = ["node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node"]
  node_bundler = "esbuild"

# Keep original path for Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Fallback for API routes if direct path doesn't work
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_api/:splat"
  status = 200
  force = false

# Fallback for all other routes - SPA mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false